apiVersion: batch/v1
kind: CronJob
metadata:
  name: statistics-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: statistics-script
            image: myscript:latest
            imagePullPolicy: Always
            env:
            - name: myapp
              value: "http://myapp-service/statistics"
          restartPolicy: OnFailure